version: '3'
services:
  nestjs:
    build:
      context: ./be
      dockerfile: Dockerfile.dev
    ports:
      - "3120:3120"
    volumes:
      - ./be:/usr/src/app
      - /usr/src/app/node_modules
      - ./be/uploads:/usr/src/app/uploads
      - ./ssl:/usr/ssl
    environment:
      - NODE_ENV=development
    command: npm run start:dev


#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
#     environment:
#       - discovery.type=single-node
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#       - xpack.security.enabled=true
#       - xpack.security.http.ssl.enabled=false
#       - xpack.security.transport.ssl.enabled=false
#       - xpack.security.authc.api_key.enabled=true
#       - ELASTIC_PASSWORD=g51i3KXTsBmoZ4ay

#     ports:
#       - 9200:9200
#     restart: always
#     volumes:
#       - ElasticSdata:/usr/share/elasticsearch/data

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.17.8
#     ports:
#       - 5601:5601
#     environment:
#       ELASTICSEARCH_URL: http://elasticsearch:9200
#       ELASTICSEARCH_USERNAME: elastic
#       ELASTICSEARCH_PASSWORD: g51i3KXTsBmoZ4ay
#     depends_on:
#       - elasticsearch

#   redis:
#     build:
#       context: ./services/redis
#       dockerfile: Dockerfile
#     container_name: redisserverx
#     ports:
#       - "6379:6379"
#     restart: always

# volumes:
#   ElasticSdata:
#     driver: local
